/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    FileUpload: typeof import('primevue/fileupload')['default']
    Form: typeof import('@primevue/forms/form')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Message: typeof import('primevue/message')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Toast: typeof import('primevue/toast')['default']
  }
}

// For TSX support
declare global {
  const Button: typeof import('primevue/button')['default']
  const FileUpload: typeof import('primevue/fileupload')['default']
  const Form: typeof import('@primevue/forms/form')['default']
  const Header: typeof import('./src/components/Header.vue')['default']
  const InputNumber: typeof import('primevue/inputnumber')['default']
  const InputText: typeof import('primevue/inputtext')['default']
  const Message: typeof import('primevue/message')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const Toast: typeof import('primevue/toast')['default']
}