/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Albums: typeof import('./src/components/layout/playlist/tabs/Albums.vue')['default']
    Badge: typeof import('./src/components/common/Badge.vue')['default']
    Button: typeof import('./src/components/common/Button.vue')['default']
    ContentArea: typeof import('./src/components/layout/ContentArea.vue')['default']
    Favorites: typeof import('./src/components/layout/playlist/tabs/Favorites.vue')['default']
    FileUpload: typeof import('primevue/fileupload')['default']
    Form: typeof import('@primevue/forms/form')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    InputText: typeof import('primevue/inputtext')['default']
    LibrarySidebar: typeof import('./src/components/sidebar/LibrarySidebar.vue')['default']
    MainPageContainer: typeof import('./src/components/layout/MainPageContainer.vue')['default']
    Message: typeof import('primevue/message')['default']
    MusicPlayingNow: typeof import('./src/components/layout/MusicPlayingNow.vue')['default']
    MusicQueueList: typeof import('./src/components/layout/MusicQueueList.vue')['default']
    NavigationContainer: typeof import('./src/components/layout/NavigationContainer.vue')['default']
    NewPlaylistButton: typeof import('./src/components/common/NewPlaylistButton.vue')['default']
    NowPlaying: typeof import('./src/components/player/NowPlaying.vue')['default']
    PlaybackBar: typeof import('./src/components/layout/PlaybackBar.vue')['default']
    PlayerControl: typeof import('./src/components/layout/PlayerControl.vue')['default']
    PlayerControll: typeof import('./src/components/PlayerControll.vue')['default']
    PlayerControls: typeof import('./src/components/layout/PlayerControls.vue')['default']
    PlaylistBackgroundCover: typeof import('./src/components/common/PlaylistBackgroundCover.vue')['default']
    PlaylistHeader: typeof import('./src/components/common/PlaylistHeader.vue')['default']
    PlaylistItem: typeof import('./src/components/common/PlaylistItem.vue')['default']
    PlaylistMusicsAsideList: typeof import('./src/components/layout/PlaylistMusicsAsideList.vue')['default']
    PrimaryNav: typeof import('./src/components/sidebar/PrimaryNav.vue')['default']
    QueueList: typeof import('./src/components/player/QueueList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Shows: typeof import('./src/components/layout/playlist/tabs/Shows.vue')['default']
    Songs: typeof import('./src/components/layout/playlist/tabs/Songs.vue')['default']
    Tab: typeof import('primevue/tab')['default']
    TabList: typeof import('primevue/tablist')['default']
    TabPanel: typeof import('primevue/tabpanel')['default']
    TabPanels: typeof import('primevue/tabpanels')['default']
    Tabs: typeof import('primevue/tabs')['default']
    Toast: typeof import('primevue/toast')['default']
    TrackHeader: typeof import('./src/components/common/TrackHeader.vue')['default']
    TrackTabs: typeof import('./src/components/common/TrackTabs.vue')['default']
    UploadAudioButton: typeof import('./src/components/common/UploadAudioButton.vue')['default']
  }
}

// For TSX support
declare global {
  const Albums: typeof import('./src/components/layout/playlist/tabs/Albums.vue')['default']
  const Badge: typeof import('./src/components/common/Badge.vue')['default']
  const Button: typeof import('./src/components/common/Button.vue')['default']
  const ContentArea: typeof import('./src/components/layout/ContentArea.vue')['default']
  const Favorites: typeof import('./src/components/layout/playlist/tabs/Favorites.vue')['default']
  const FileUpload: typeof import('primevue/fileupload')['default']
  const Form: typeof import('@primevue/forms/form')['default']
  const Header: typeof import('./src/components/Header.vue')['default']
  const InputNumber: typeof import('primevue/inputnumber')['default']
  const InputText: typeof import('primevue/inputtext')['default']
  const LibrarySidebar: typeof import('./src/components/sidebar/LibrarySidebar.vue')['default']
  const MainPageContainer: typeof import('./src/components/layout/MainPageContainer.vue')['default']
  const Message: typeof import('primevue/message')['default']
  const MusicPlayingNow: typeof import('./src/components/layout/MusicPlayingNow.vue')['default']
  const MusicQueueList: typeof import('./src/components/layout/MusicQueueList.vue')['default']
  const NavigationContainer: typeof import('./src/components/layout/NavigationContainer.vue')['default']
  const NewPlaylistButton: typeof import('./src/components/common/NewPlaylistButton.vue')['default']
  const NowPlaying: typeof import('./src/components/player/NowPlaying.vue')['default']
  const PlaybackBar: typeof import('./src/components/layout/PlaybackBar.vue')['default']
  const PlayerControl: typeof import('./src/components/layout/PlayerControl.vue')['default']
  const PlayerControll: typeof import('./src/components/PlayerControll.vue')['default']
  const PlayerControls: typeof import('./src/components/layout/PlayerControls.vue')['default']
  const PlaylistBackgroundCover: typeof import('./src/components/common/PlaylistBackgroundCover.vue')['default']
  const PlaylistHeader: typeof import('./src/components/common/PlaylistHeader.vue')['default']
  const PlaylistItem: typeof import('./src/components/common/PlaylistItem.vue')['default']
  const PlaylistMusicsAsideList: typeof import('./src/components/layout/PlaylistMusicsAsideList.vue')['default']
  const PrimaryNav: typeof import('./src/components/sidebar/PrimaryNav.vue')['default']
  const QueueList: typeof import('./src/components/player/QueueList.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const Shows: typeof import('./src/components/layout/playlist/tabs/Shows.vue')['default']
  const Songs: typeof import('./src/components/layout/playlist/tabs/Songs.vue')['default']
  const Tab: typeof import('primevue/tab')['default']
  const TabList: typeof import('primevue/tablist')['default']
  const TabPanel: typeof import('primevue/tabpanel')['default']
  const TabPanels: typeof import('primevue/tabpanels')['default']
  const Tabs: typeof import('primevue/tabs')['default']
  const Toast: typeof import('primevue/toast')['default']
  const TrackHeader: typeof import('./src/components/common/TrackHeader.vue')['default']
  const TrackTabs: typeof import('./src/components/common/TrackTabs.vue')['default']
  const UploadAudioButton: typeof import('./src/components/common/UploadAudioButton.vue')['default']
}